version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gosampledb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
